// This is an autogenerated file, do not edit
package ast

import "github.com/cedricmar/bazic/pkg/scanner"

// Expr is a type for the AST
type Expr Accepter

type Accepter interface {
	Accept(v Visitor) interface{}
}

// Visitor allows to add features to Types
type Visitor interface {
	VisitBinaryExpr(expr Binary) interface{}
	VisitGroupingExpr(expr Grouping) interface{}
	VisitLiteralExpr(expr Literal) interface{}
	VisitUnaryExpr(expr Unary) interface{}
}

// Binary is a node of the AST
type Binary struct {
	left     Expr
	operator scanner.Token
	right    Expr
}

// NewBinary returns a new node of type Binary
func NewBinary(left Expr, operator scanner.Token, right Expr) Binary {
	return Binary{
		left:     left,
		operator: operator,
		right:    right,
	}
}

func (b Binary) Accept(v Visitor) interface{} {
	return v.VisitBinaryExpr(b)
}

// Grouping is a node of the AST
type Grouping struct {
	expression Expr
}

// NewGrouping returns a new node of type Grouping
func NewGrouping(expression Expr) Grouping {
	return Grouping{
		expression: expression,
	}
}

func (g Grouping) Accept(v Visitor) interface{} {
	return v.VisitGroupingExpr(g)
}

// Literal is a node of the AST
type Literal struct {
	value interface{}
}

// NewLiteral returns a new node of type Literal
func NewLiteral(value interface{}) Literal {
	return Literal{
		value: value,
	}
}

func (l Literal) Accept(v Visitor) interface{} {
	return v.VisitLiteralExpr(l)
}

// Unary is a node of the AST
type Unary struct {
	operator scanner.Token
	right    Expr
}

// NewUnary returns a new node of type Unary
func NewUnary(operator scanner.Token, right Expr) Unary {
	return Unary{
		operator: operator,
		right:    right,
	}
}

func (u Unary) Accept(v Visitor) interface{} {
	return v.VisitUnaryExpr(u)
}
